<h1>Mecânicas de jogo</h1>
<p>Em uma partida de RPG, o narrador inicia a narrativa, situando os protagonistas (personagens dos jogadores) na aventura. À medida que a história se desenrola, o narrador apresenta desafios que exigem decisões por parte dos protagonistas. Muitos eventos no jogo são resolvidos na camada narrativa, onde o narrador descreve a situação, os jogadores detalham as ações de seus personagens, e o narrador determina o desfecho dessas escolhas. No entanto, em vários casos, seria arbitrário que o desfecho dependesse apenas da decisão do narrador. Para evitar isso, são solicitados testes com dados, permitindo que o acaso desempenhe esse papel de árbitro.</p>
<p>Este capítulo tem como objetivo exemplificar como o narrador pode lidar com as diversas possibilidades de testes que podem surgir e como usar as mecânicas descritas aqui como ferramentas para arbitrar situações. É possível que o narrador enfrente situações para as quais ainda não existem regras definidas, e nesses casos, caberá a ele criar soluções adequadas.</p>
<p>O combate demanda um quantidade grande de regras, e por esse motivo está separado em um capítulo.</p>

<h2>Quando realizar testes</h2>

<p>Sempre que o narrador considerar sensato resolver uma situa&ccedil;&atilde;o sem recorrer a um teste, ele deve faz&ecirc;-lo, pois os testes podem atrasar a narrativa e prejudicar o dinamismo da partida. No entanto, como mencionado anteriormente, muitas situa&ccedil;&otilde;es n&atilde;o ter&atilde;o um desfecho evidente, e nessas circunst&acirc;ncias, o narrador deve utilizar os testes para determinar o resultado.</p>

<p>Suponhamos que o grupo de protagonistas esteja observando furtivamente o acampamento inimigo. Um deles tem a ideia de atirar uma tocha em uma tenda que est&aacute; a quinze metros de dist&acirc;ncia, visando for&ccedil;ar os inimigos a sa&iacute;rem devido ao fogo, pegando-os de surpresa. O narrador n&atilde;o precisa solicitar um teste de destreza para verificar se a tocha acerta a tenda; esse tipo de a&ccedil;&atilde;o pode ser considerado um acerto autom&aacute;tico, permitindo que a narrativa prossiga.</p>

<p>Agora, suponhamos que um dos capangas inimigos esteja sentado em uma banqueta ao lado da tenda, fumando seu cachimbo. Em vez de lan&ccedil;ar uma tocha na tenda, o personagem decide se aproximar sorrateiramente desse capanga, sem fazer barulho, e desferir-lhe uma facada pelas costas. Essa a&ccedil;&atilde;o depende muito mais da destreza do personagem, e n&atilde;o cabe ao narrador determinar o resultado. Nesse caso, &eacute; apropriado que o narrador solicite um teste de furtividade.</p>

<p>Em resumo, o narrador deve realizar o m&iacute;nimo poss&iacute;vel de testes para manter o dinamismo da partida, mas deve conduzir os testes necess&aacute;rios para evitar tornar-se autorit&aacute;rio.</p>

<img src="<?=base_url('assets/img/sistema/coragem.png')?>" alt="">

<h2>Como fazer um teste</h2>
<p>Durante o desenrolar do jogo, os jogadores serão demandados pelo narrador a testar as habilidades de seus personagens ao executarem tarefas específicas, e isso quase sempre será feito por meio de um teste de atributo. Realizar um teste de atributo é uma ação simples: o jogador lança um dado de 20 lados (d20) e precisa obter um valor igual ou inferior ao atributo mais relevante para a ação, para alcançar o sucesso. Caso contrário, o teste será considerado um fracasso.</p>
<p>Vamos considerar que o personagem esteja tentando determinar se um vegetal encontrado é seguro para consumo ou não. Cabe ao narrador escolher qual atributo está associado a essa tarefa, e como se trata de uma ação relacionada ao conhecimento, o teste de sabedoria deve ser o indicado.</p>
<p>Em caso de sucesso ou fracasso, deve-se verificar de quanto pontos foi a diferença entre o valor do dado e valor do atributo. O quanto maior for essa diferença, maior foi o erro ou acerto. Uma diferença de até 4 pontos é considerada normal, de 5 a 9 pontos alta, e acima de 9 crítica. O narrador deverá considerar o tamanho dessa diferença pra determinar o quão bom ou ruim foi o acerto.&nbsp;</p>
<p>Independente do valor a ser testado, um teste em que se obtenha 1, 2 ou 3 no dado será sempre um acerto, e obtendo-se 18, 19 ou 20 será sempre um erro.</p>

<h2>Testando com vantagem e desvantagem</h2>
<p>Alguns momentos, situações ou virtudes de personagem podem indicar que o jogador deverá fazer o teste com vantagem ou desvantagem. Um teste com vantagem aumenta muito as chances de acerto, e com desvantagem reduz muito.</p>
<p>Para realizar um teste com vantagem deve-se, ao invés de jogar apenas 1d20, jogar 2d20 e escolher o menor valor. Já a jogada com desvantagem é o inverso, deve-se escolher o dado com maior valor. Caso a jogada tenha vantagem e desvantagem, faça apenas a jogada normalmente. No mais, vantagens e desvantagens não se somam, ou seja, não existe vantangem ou desvantagem dupla, jogando 3 dados, por exemplo.</p>

<h2>Bônus e penalidades</h2>
<p>Na maioria dos testes de atributo, bônus e penalidades são aplicados para tornar mais fácil ou difícil obter um resultado positivo. Se o personagem tiver uma habilidade relevante ao teste, o nível dessa habilidade será adicionado como bônus à jogada. As armas também fornecem bônus, dependendo do atributo utilizado para atacar. Além disso, o narrador pode conceder bônus extras se acreditar que o teste está sendo facilitado por alguma circunstância específica. Da mesma forma, sempre que o narrador entender que algo torna o teste mais desafiador, ele deve aplicar uma penalidade. No caso de um ataque, a guarda do oponente é usada como penalidade.</p>
<p>O valor do bônus é somado ao atributo que será testado. Como o objetivo é obter um valor igual ou menor que o atributo para ter sucesso, aumentar o valor do atributo com um bônus facilita a jogada. Uma penalidade pode ser aplicada de duas maneiras: ou reduzindo o valor do atributo, ou somando-a ao resultado do dado. O jogador pode escolher a forma mais conveniente.</p>
<p>Por exemplo, se o personagem está rastreando pegadas de um inimigo, o narrador pede um teste de sabedoria. O personagem possui a habilidade de rastreamento no nível 3, o que concede um bônus de 3 nesse teste. Se a sabedoria do personagem for 12, ele pode considerá-la como 15 para o teste. No entanto, está chovendo, e a chuva dificultou a leitura das pegadas, então o narrador aplica uma penalidade de 4 pontos. O jogador deverá, portanto, considerar a sabedoria como 11 para esse teste. Em seguida, ele rola um d20 e verifica se consegue um resultado igual ou inferior a 11.</p>
<p>Em um ataque, o jogador deve escolher qual atributo disponível para a arma será utilizado. Supondo que ele escolha destreza, e a arma conceda um bônus de 3 para destreza, se a destreza do personagem for 12, ele a considera como 15 para o ataque. Além disso, o personagem evoluiu sua habilidade com espada curta até o nível 3, o que aumenta a chance de acerto para 18. O jogador então pergunta a guarda do oponente, e o narrador responde que é 5. Esse valor é subtraído da chance de acerto, resultando em 13. Assim, se o jogador rolar 13 ou menos no dado, o ataque será bem-sucedido.</p>

<h2>Intensidade do acerto ou erro</h2>
<p>Sempre que um teste for realizado, a diferença entre o valor obtido no dado e o valor necessário determinará a intensidade do sucesso ou fracasso. Para obter sucesso, o jogador precisa rolar um valor no d20 igual ou menor ao estipulado pelo narrador. Se o valor for exatamente o necessário, o teste será bem-sucedido, mas por uma margem estreita. Se o resultado for 4 pontos abaixo do necessário, o sucesso será considerado bom; com 8 pontos a menos, quase perfeito; e uma diferença superior a 10 indicará um sucesso absoluto. A mesma lógica se aplica aos erros: quanto maior a diferença, mais grave será o fracasso.</p>
<p>Em muitas jogadas, essa diferença influenciará diretamente no efeito obtido. Em um ataque, quanto maior o sucesso, maior será o dano causado. Em testes de alquimia, graça divina ou poder oculto, a intensidade do sucesso também será proporcional ao resultado. Já em outras jogadas, a intensidade não terá um impacto numérico direto, mas afetará a narrativa. Ao investigar uma cena de crime, por exemplo, o personagem pode encontrar mais ou menos evidências de acordo com o valor obtido. Em um teste de barganha, um sucesso maior pode resultar em preços melhores. Cabe ao narrador determinar o impacto da intensidade do resultado, inclusive no caso de falhas, onde uma diferença maior pode acarretar consequências mais severas. Em uma negociação, por exemplo, um grande erro pode ofender o vendedor, fazendo com que ele aumente os preços.</p>

<h2>Situações Específicas</h2>
<p>A seguir, discutimos situações comuns em aventuras e como o narrador pode lidar com elas. Ações como escalar, equilibrar-se, andar furtivamente, saltar e acertar alvos geralmente envolvem testes de destreza. Desafios físicos, como levantar objetos pesados, empurrar adversários ou escalar sem apoio, estão ligados à força. Tarefas de persuasão, investigação, atuação, percepção e leitura de intenções são associadas à astúcia. Atividades como montar acampamento, rastrear animais, tratar ferimentos, cozinhar, ler, escrever e identificar itens dependem da sabedoria. Resistência a venenos ou corridas de longa distância envolvem testes de constituição, enquanto sorte e interações com itens mágicos são determinados pelo karma.</p>
<h4>Andar Furtivamente</h4>
<p>Ao lidar com situações furtivas (movimentação silenciosa), o narrador decide se um teste é necessário. Se for, fatores como a armadura, tipo de solo e proximidade de possíveis ouvintes podem influenciar, resultando em penalidades.</p>
<h4>Identificar Armadilhas ou Passagens Secretas</h4>
<p>O teste para identificar armadilhas ou passagens secretas envolve astúcia. O narrador deve pedir aos jogadores que descrevam como seus personagens estão procurando. Respostas genéricas podem resultar em penalidades elevadas, como -10. Se a descrição for mais precisa, como "examinar a parede direita", um teste normal pode ser feito. Se o jogador detalha: "vou passar a mão sobre as pedras da parede do fundo, procurando uma que possa ser empurrada", e o mecanismo estiver nas pedras, o narrador pode conceder o sucesso sem exigir teste.</p>
<h4>Persuadir ou Enganar</h4>
<p>Persuadir ou enganar também envolve um teste de astúcia. O narrador deve considerar a qualidade do argumento apresentado pelos jogadores. Um argumento convincente pode permitir um teste sem penalidades, enquanto um argumento fraco pode ser tratado como uma falha automática. O desafio deve equilibrar a narrativa com as habilidades dos personagens.</p>
<h4>Testar a Sorte</h4>
<p>Em muitos momentos, o narrador pode precisar testar a sorte dos personagens. Por exemplo, ao caminhar por um corredor com uma armadilha, o narrador decide quem será atingido com um teste de karma. Se a armadilha afetar uma pessoa, o personagem com o pior resultado será atingido. Se a armadilha afetar vários, todos que falharem no teste de karma sofrerão as consequências. Essa é uma maneira criativa de usar o acaso para determinar os resultados.</p>
<h4>Realizar Saltos</h4>
<p>Se o grupo encontrar uma ponte danificada e precisar saltar, o narrador pode solicitar um teste de moral para verificar se o personagem tem coragem suficiente. Em caso de falha, ele se recusará a saltar. O teste de salto em si envolve destreza, mas fatores como carga, ferimentos e a distância a ser saltada podem gerar penalidades. Uma distância curta pode oferecer bônus, uma distância média requer um teste sem penalidades, e uma longa pode impor uma penalidade, que também pode ser aplicada no teste de moral.</p>
<h4>Arremesso de Objetos</h4>
<p>O arremesso de objetos pode ser uma ação ambígua. Para arremessar um objeto leve, usa-se um teste de destreza, com a distância aumentando a penalidade. No caso de um objeto pesado, a precisão não é o foco, pois a distância é limitada pelo peso, e o teste de força pode ser mais adequado. Para objetos de peso mediano, o narrador pode exigir testes de força e destreza, avaliando tanto a distância quanto a precisão.</p>
<h4>Teste de Coragem</h4>
<p>Em certos momentos, o narrador pode precisar determinar se o personagem tem coragem suficiente para realizar uma tarefa, como saltar sobre um abismo. Para isso, solicita-se um teste de moral. O jogador rola um d20 e, se o resultado for igual ou inferior à moral atual do personagem, ele terá coragem para executar a ação.</p>

<img src="<?=base_url('assets/img/sistema/procurando_passagem.png')?>" alt="">

<h2>Intervenção narrativa</h2>
<p>Cada jogador define apenas as ações de seu personagem; os demais personagens, criaturas, ambientes e acontecimentos do cenário são funções do narrador da aventura. A mecânica de intervenção narrativa existe para permitir que os jogadores possam alterar o ambiente a fim de favorecê-los, fazendo uma pequena intervenção narrativa.</p>
<p>Imagine que os personagens estão a muitos quilômetros de qualquer cidade e descobrem uma caverna. Ao entrar na caverna, o narrador descreve-a como completamente escura. Os jogadores percebem que não possuem nenhum equipamento ou forma de iluminar aquele ambiente. Nesse caso, um dos jogadores opta por fazer uma intervenção narrativa e diz que, na verdade, na entrada desta caverna, havia uma mochila com equipamentos jogados no chão (o que seria muito conveniente para o grupo). Nesse caso, um teste de karma decidirá se a intervenção procederá ou não.</p>
<p>O processo funciona da seguinte maneira: o jogador diz qual intervenção pretende fazer, e o narrador define uma penalidade para aquele teste. Caso aceite o desafio, o jogador reduz em 1 ponto sua moral e realiza o teste de karma. Em caso de acerto, o trecho narrado é real; caso contrário, a coisa acontece apenas na cabeça do personagem, como uma miragem inofensiva. Entretanto, as forças do Miska lhe aplicarão a lei do retorno, que será definida pelo narrador.</p>
<p>O retorno em caso de erro deve ser proporcional à intervenção pretendida. No caso do exemplo anterior, o narrador pode fazer com que o personagem esqueça de algum equipamento importante no futuro, e ele só se dará conta quando precisar dele.</p>
<p>O narrador deve definir uma penalidade para o teste. Pensando ainda sobre o exemplo anterior, caso aquela caverna seja frequentada de forma muito constante por viajantes, isso poderia gerar um teste com bônus, mas caso seja pouco frequentada, sem penalidade; já se a caverna foi frequentada por pouquíssimas pessoas, 3 ou 4 de penalidade pode ser uma boa dose, e se a caverna nunca foi frequentada por humanos, o narrador pode considerar a intervenção impossível. A penalidade deve ser indicada antes do jogador gastar seu ponto de moral, e caberá a ele aceitar o desafio.</p>
